CREATE TABLE `users`(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `last_name` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `country` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1=Active | 0=Inactive',
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into users (id, first_name, last_name, email, country, status) values (1, 'Mela', 'Stit', 'mstit0@youtu.be', 'Spain', 1);
insert into users (id, first_name, last_name, email, country, status) values (2, 'Holly-anne', 'Reyne', 'hreyne1@fda.gov', 'Spain', 2);
insert into users (id, first_name, last_name, email, country, status) values (3, 'Marla', 'Scothern', 'mscothern2@mlb.com', 'Spain', 3);
insert into users (id, first_name, last_name, email, country, status) values (4, 'Nathan', 'Kerkham', 'nkerkham3@baidu.com', 'Spain', 4);
insert into users (id, first_name, last_name, email, country, status) values (5, 'Donielle', 'Shorto', 'dshorto4@cdc.gov', 'Spain', 5);
insert into users (id, first_name, last_name, email, country, status) values (6, 'Kendell', 'March', 'kmarch5@cnn.com', 'Spain', 6);
insert into users (id, first_name, last_name, email, country, status) values (7, 'Edd', 'Servis', 'eservis6@stanford.edu', 'Spain', 7);
insert into users (id, first_name, last_name, email, country, status) values (8, 'Fredric', 'Cregeen', 'fcregeen7@oracle.com', 'Spain', 8);
insert into users (id, first_name, last_name, email, country, status) values (9, 'Augustus', 'Kewish', 'akewish8@behance.net', 'Spain', 9);
insert into users (id, first_name, last_name, email, country, status) values (10, 'Matthew', 'Crossingham', 'mcrossingham9@nasa.gov', 'Spain', 10);
insert into users (id, first_name, last_name, email, country, status) values (11, 'Barnaby', 'Weed', 'bweeda@hc360.com', 'Spain', 11);
insert into users (id, first_name, last_name, email, country, status) values (12, 'Cobbie', 'Spinke', 'cspinkeb@goo.ne.jp', 'Spain', 12);
insert into users (id, first_name, last_name, email, country, status) values (13, 'Kenneth', 'Pasby', 'kpasbyc@wp.com', 'Spain', 13);
insert into users (id, first_name, last_name, email, country, status) values (14, 'Evan', 'Dukelow', 'edukelowd@marriott.com', 'Spain', 14);
insert into users (id, first_name, last_name, email, country, status) values (15, 'Ronnie', 'Ridel', 'rridele@instagram.com', 'Spain', 15);
insert into users (id, first_name, last_name, email, country, status) values (16, 'Edeline', 'Riddington', 'eriddingtonf@deliciousdays.com', 'Spain', 16);
insert into users (id, first_name, last_name, email, country, status) values (17, 'Levi', 'Dolligon', 'ldolligong@sfgate.com', 'Spain', 17);
insert into users (id, first_name, last_name, email, country, status) values (18, 'Petrina', 'Hamlington', 'phamlingtonh@go.com', 'Spain', 18);
insert into users (id, first_name, last_name, email, country, status) values (19, 'Tracey', 'Chene', 'tchenei@networkadvertising.org', 'Spain', 19);
insert into users (id, first_name, last_name, email, country, status) values (20, 'Hillyer', 'Wharby', 'hwharbyj@cargocollective.com', 'Spain', 20);
insert into users (id, first_name, last_name, email, country, status) values (21, 'Alethea', 'McIlmurray', 'amcilmurrayk@usgs.gov', 'Spain', 21);
insert into users (id, first_name, last_name, email, country, status) values (22, 'Dorian', 'Pyffe', 'dpyffel@independent.co.uk', 'Spain', 22);
insert into users (id, first_name, last_name, email, country, status) values (23, 'Mariya', 'Maggs', 'mmaggsm@issuu.com', 'Spain', 23);
insert into users (id, first_name, last_name, email, country, status) values (24, 'Katinka', 'Mamwell', 'kmamwelln@google.cn', 'Spain', 24);
insert into users (id, first_name, last_name, email, country, status) values (25, 'Lauri', 'Bosket', 'lbosketo@wsj.com', 'Spain', 25);
insert into users (id, first_name, last_name, email, country, status) values (26, 'Giovanna', 'Gummory', 'ggummoryp@flavors.me', 'Spain', 26);
insert into users (id, first_name, last_name, email, country, status) values (27, 'Tory', 'Pitford', 'tpitfordq@yellowbook.com', 'Spain', 27);
insert into users (id, first_name, last_name, email, country, status) values (28, 'Abe', 'Simco', 'asimcor@infoseek.co.jp', 'Spain', 28);
insert into users (id, first_name, last_name, email, country, status) values (29, 'Yvor', 'Mulles', 'ymulless@aol.com', 'Spain', 29);
insert into users (id, first_name, last_name, email, country, status) values (30, 'Jasun', 'Dmiterko', 'jdmiterkot@europa.eu', 'Spain', 30);
insert into users (id, first_name, last_name, email, country, status) values (31, 'Lanae', 'McKeand', 'lmckeandu@ucsd.edu', 'Spain', 31);
insert into users (id, first_name, last_name, email, country, status) values (32, 'Lorna', 'McGavigan', 'lmcgaviganv@nasa.gov', 'Spain', 32);
insert into users (id, first_name, last_name, email, country, status) values (33, 'Matty', 'Edwardson', 'medwardsonw@webmd.com', 'Spain', 33);
insert into users (id, first_name, last_name, email, country, status) values (34, 'Dougie', 'Alvarado', 'dalvaradox@ibm.com', 'Spain', 34);
insert into users (id, first_name, last_name, email, country, status) values (35, 'Barbaraanne', 'Battany', 'bbattanyy@unc.edu', 'Spain', 35);
insert into users (id, first_name, last_name, email, country, status) values (36, 'Johnathan', 'Humblestone', 'jhumblestonez@mlb.com', 'Spain', 36);
insert into users (id, first_name, last_name, email, country, status) values (37, 'Kimmie', 'Ovitz', 'kovitz10@xrea.com', 'Spain', 37);
insert into users (id, first_name, last_name, email, country, status) values (38, 'Eldon', 'Salters', 'esalters11@paginegialle.it', 'Spain', 38);
insert into users (id, first_name, last_name, email, country, status) values (39, 'Angie', 'Tambling', 'atambling12@nymag.com', 'Spain', 39);
insert into users (id, first_name, last_name, email, country, status) values (40, 'Nissie', 'Parrett', 'nparrett13@elegantthemes.com', 'Spain', 40);
insert into users (id, first_name, last_name, email, country, status) values (41, 'Benny', 'Duffet', 'bduffet14@businessweek.com', 'Spain', 41);
insert into users (id, first_name, last_name, email, country, status) values (42, 'Alena', 'Bulward', 'abulward15@phpbb.com', 'Spain', 42);
insert into users (id, first_name, last_name, email, country, status) values (43, 'Carolus', 'Pallas', 'cpallas16@feedburner.com', 'Spain', 43);
insert into users (id, first_name, last_name, email, country, status) values (44, 'Audre', 'Manjin', 'amanjin17@yandex.ru', 'Spain', 44);
insert into users (id, first_name, last_name, email, country, status) values (45, 'Morgana', 'McCritichie', 'mmccritichie18@phpbb.com', 'Spain', 45);
insert into users (id, first_name, last_name, email, country, status) values (46, 'Alexio', 'Dowry', 'adowry19@intel.com', 'Spain', 46);
insert into users (id, first_name, last_name, email, country, status) values (47, 'Alejandrina', 'Rowthorn', 'arowthorn1a@desdev.cn', 'Spain', 47);
insert into users (id, first_name, last_name, email, country, status) values (48, 'Jasen', 'Kneale', 'jkneale1b@ovh.net', 'Spain', 48);
insert into users (id, first_name, last_name, email, country, status) values (49, 'Ralf', 'Gatward', 'rgatward1c@europa.eu', 'Spain', 49);
insert into users (id, first_name, last_name, email, country, status) values (50, 'Grantham', 'Kliment', 'gkliment1d@ycombinator.com', 'Spain', 50);
insert into users (id, first_name, last_name, email, country, status) values (51, 'Sheba', 'Pellissier', 'spellissier1e@wikimedia.org', 'Spain', 51);
insert into users (id, first_name, last_name, email, country, status) values (52, 'Trixy', 'Tenney', 'ttenney1f@edublogs.org', 'Spain', 52);
insert into users (id, first_name, last_name, email, country, status) values (53, 'Jacquelynn', 'Rawe', 'jrawe1g@mozilla.com', 'Spain', 53);
insert into users (id, first_name, last_name, email, country, status) values (54, 'Cosetta', 'Fairfoul', 'cfairfoul1h@exblog.jp', 'Spain', 54);
insert into users (id, first_name, last_name, email, country, status) values (55, 'Rivkah', 'Abelevitz', 'rabelevitz1i@ebay.co.uk', 'Spain', 55);
insert into users (id, first_name, last_name, email, country, status) values (56, 'Scarface', 'Devoy', 'sdevoy1j@github.com', 'Spain', 56);
insert into users (id, first_name, last_name, email, country, status) values (57, 'Rodolphe', 'Sicha', 'rsicha1k@geocities.jp', 'Spain', 57);
insert into users (id, first_name, last_name, email, country, status) values (58, 'Carroll', 'Sydes', 'csydes1l@howstuffworks.com', 'Spain', 58);
insert into users (id, first_name, last_name, email, country, status) values (59, 'Cordelie', 'Bains', 'cbains1m@hostgator.com', 'Spain', 59);
insert into users (id, first_name, last_name, email, country, status) values (60, 'Estella', 'Oehm', 'eoehm1n@simplemachines.org', 'Spain', 60);
insert into users (id, first_name, last_name, email, country, status) values (61, 'Daron', 'Monard', 'dmonard1o@goo.ne.jp', 'Spain', 61);
insert into users (id, first_name, last_name, email, country, status) values (62, 'Hillery', 'Britt', 'hbritt1p@time.com', 'Spain', 62);
insert into users (id, first_name, last_name, email, country, status) values (63, 'Yvon', 'Fancet', 'yfancet1q@house.gov', 'Spain', 63);
insert into users (id, first_name, last_name, email, country, status) values (64, 'Samara', 'Zoanetti', 'szoanetti1r@comcast.net', 'Spain', 64);
insert into users (id, first_name, last_name, email, country, status) values (65, 'Sam', 'Ludlamme', 'sludlamme1s@nationalgeographic.com', 'Spain', 65);
insert into users (id, first_name, last_name, email, country, status) values (66, 'Stefa', 'Buttrum', 'sbuttrum1t@pen.io', 'Spain', 66);
insert into users (id, first_name, last_name, email, country, status) values (67, 'Jordon', 'Wittey', 'jwittey1u@loc.gov', 'Spain', 67);
insert into users (id, first_name, last_name, email, country, status) values (68, 'Lindsey', 'Pughsley', 'lpughsley1v@angelfire.com', 'Spain', 68);
insert into users (id, first_name, last_name, email, country, status) values (69, 'Lari', 'Dils', 'ldils1w@dagondesign.com', 'Spain', 69);
insert into users (id, first_name, last_name, email, country, status) values (70, 'Alfons', 'Kinglake', 'akinglake1x@cornell.edu', 'Spain', 70);
insert into users (id, first_name, last_name, email, country, status) values (71, 'Lionello', 'Pedro', 'lpedro1y@twitter.com', 'Spain', 71);
insert into users (id, first_name, last_name, email, country, status) values (72, 'Chandra', 'Dell', 'cdell1z@biblegateway.com', 'Spain', 72);
insert into users (id, first_name, last_name, email, country, status) values (73, 'Jolene', 'Elfe', 'jelfe20@flickr.com', 'Spain', 73);
insert into users (id, first_name, last_name, email, country, status) values (74, 'Benedikta', 'Wyeth', 'bwyeth21@ibm.com', 'Spain', 74);
insert into users (id, first_name, last_name, email, country, status) values (75, 'Land', 'Ivanikov', 'livanikov22@boston.com', 'Spain', 75);
insert into users (id, first_name, last_name, email, country, status) values (76, 'Tan', 'Tew', 'ttew23@i2i.jp', 'Spain', 76);
insert into users (id, first_name, last_name, email, country, status) values (77, 'Bertrando', 'Brideaux', 'bbrideaux24@biglobe.ne.jp', 'Spain', 77);
insert into users (id, first_name, last_name, email, country, status) values (78, 'Sonny', 'Waddy', 'swaddy25@time.com', 'Spain', 78);
insert into users (id, first_name, last_name, email, country, status) values (79, 'Humbert', 'Walford', 'hwalford26@ifeng.com', 'Spain', 79);
insert into users (id, first_name, last_name, email, country, status) values (80, 'Darius', 'Butte', 'dbutte27@sbwire.com', 'Spain', 80);
insert into users (id, first_name, last_name, email, country, status) values (81, 'Bertina', 'Corballis', 'bcorballis28@adobe.com', 'Spain', 81);
insert into users (id, first_name, last_name, email, country, status) values (82, 'Wileen', 'Lambillion', 'wlambillion29@whitehouse.gov', 'Spain', 82);
insert into users (id, first_name, last_name, email, country, status) values (83, 'Loren', 'Solland', 'lsolland2a@odnoklassniki.ru', 'Spain', 83);
insert into users (id, first_name, last_name, email, country, status) values (84, 'Angelique', 'Rochester', 'arochester2b@blogspot.com', 'Spain', 84);
insert into users (id, first_name, last_name, email, country, status) values (85, 'Lonna', 'Daggett', 'ldaggett2c@spiegel.de', 'Spain', 85);
insert into users (id, first_name, last_name, email, country, status) values (86, 'Almeta', 'Blackbourn', 'ablackbourn2d@springer.com', 'Spain', 86);
insert into users (id, first_name, last_name, email, country, status) values (87, 'Bobette', 'Piggin', 'bpiggin2e@businessweek.com', 'Spain', 87);
insert into users (id, first_name, last_name, email, country, status) values (88, 'Orion', 'Ganiford', 'oganiford2f@ucla.edu', 'Spain', 88);
insert into users (id, first_name, last_name, email, country, status) values (89, 'Matthew', 'Fidge', 'mfidge2g@yandex.ru', 'Spain', 89);
insert into users (id, first_name, last_name, email, country, status) values (90, 'Khalil', 'Creboe', 'kcreboe2h@mapquest.com', 'Spain', 90);
insert into users (id, first_name, last_name, email, country, status) values (91, 'Raf', 'Grinnov', 'rgrinnov2i@youku.com', 'Spain', 91);
insert into users (id, first_name, last_name, email, country, status) values (92, 'Delora', 'Cote', 'dcote2j@meetup.com', 'Spain', 92);
insert into users (id, first_name, last_name, email, country, status) values (93, 'Amalea', 'Baumadier', 'abaumadier2k@instagram.com', 'Spain', 93);
insert into users (id, first_name, last_name, email, country, status) values (94, 'Farra', 'Wenden', 'fwenden2l@who.int', 'Spain', 94);
insert into users (id, first_name, last_name, email, country, status) values (95, 'Amandi', 'Longhorne', 'alonghorne2m@elpais.com', 'Spain', 95);
insert into users (id, first_name, last_name, email, country, status) values (96, 'Sharity', 'Polotti', 'spolotti2n@bbc.co.uk', 'Spain', 96);
insert into users (id, first_name, last_name, email, country, status) values (97, 'Layton', 'Lancley', 'llancley2o@pcworld.com', 'Spain', 97);
insert into users (id, first_name, last_name, email, country, status) values (98, 'Daniele', 'Dobney', 'ddobney2p@slashdot.org', 'Spain', 98);
insert into users (id, first_name, last_name, email, country, status) values (99, 'Fields', 'Custed', 'fcusted2q@icq.com', 'Spain', 99);
insert into users (id, first_name, last_name, email, country, status) values (100, 'Farrell', 'MacCole', 'fmaccole2r@freewebs.com', 'Spain', 100);